#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc config focused_border_color "#aaaaaa"
bspc config normal_border_color "#333333"
bspc config active_border_color "#333333"

setxkbmap -layout no &
picom -b &
~/.fehbg &
nm-applet &
/usr/bin/dunst &
batsignal -w 20 -c 5 &
light-locker &
optimus-manager-qt &
redshift-gtk -l 60:10 &
~/.config/polybar/launch.sh &
